config/routes.rb
Rails.application.routes.draw do
  root to: "surveys#index"

  resources :surveys do
    resources :range_questions,
              defaults: { q_type: 'RangeQuestion'},
              except: [:index, :show], shallow: :true

    resources :mc_questions,
              defaults: { q_type: 'McQuestion'},
              except: [:index, :show], shallow: :true

    resources :questions,
              only: [:index], shallow: :true

    resources :survey_responses, only: [:new, :create], shallow: :true

    resources :results, only: [:show], shallow: :true

  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  belongs_to :question, polymorphic: true
  has_many :question_responses
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @survey = Survey.find(params[:survey_id])
  end


end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_links.html.erb
<%= link_to 'Edit Survey Title/Description', edit_survey_path(@survey.id) %><br>
<%= link_to 'Delete Survey',  @survey,  method: :delete, data: { confirm: 'Are you sure?' } %>
<br><hr>

<%= link_to "<button class='btn btn-warning'>Take Survey</button>".html_safe, new_survey_survey_response_path %>
<%= link_to "<button class='btn btn-info'>View Survey Results</button>".html_safe, result_path(@survey.id) %>

<br><hr>
<h3>New Question</h3>
<%= link_to "<button class='btn btn-primary'>New Multiple Choice Question</button>".html_safe, new_survey_mc_question_path %>
<%= link_to "<button class='btn btn-success'>New Range Type Question</button>".html_safe, new_survey_range_question_path %>

<br>
<hr>

app/views/questions/_mc_options.html.erb
Options:
<ul>
  <% get_question_object(question).options.each do |option| %>

    <li><%= option.option %></li>
  <% end %>

</ul>

app/views/questions/_range_options.html.erb
Range:
<ul>
  <li>Min: <%=  get_question_object(question).min %></li>
  <li>Max: <%=  get_question_object(question).max %></li>
</ul>

app/views/questions/index.html.erb
<h1><%= @survey.title %></h1>
<h3><%= @survey.description %></h3>

<%= render 'links' %>

<% @survey.questions.each do |question| %>

  <h5>Question: <%= get_question_object(question).question_text %></h5>

    <% if get_question_object(question).class.name == 'McQuestion' %>
      Type: Multiple Choice <br>

      <%= render 'mc_options', question: question %>
      <%= link_to 'Edit Question', edit_mc_question_path(get_question_object(question).id) %>
      <br>
      <%= link_to 'Delete Question',
          { action: 'destroy', controller: 'mc_questions', id: get_question_object(question).id },
            method: :delete,
              data: { confirm: 'Are you sure?' } %>
      <br>


    <% else %>
      Type: Range <br>

      <%= render 'range_options', question: question %>
       <%= link_to 'Edit Question', edit_range_question_path(get_question_object(question).id) %><br>
        <%= link_to 'Delete Question',
          { action: 'destroy', controller: 'range_questions', id: get_question_object(question).id },
            method: :delete,
              data: { confirm: 'Are you sure?' } %>
    <% end %>


  <hr>
<% end %>