config/routes.rb
Rails.application.routes.draw do
  root to: "surveys#index"

  resources :surveys do
    resources :range_questions,
              defaults: { q_type: 'RangeQuestion'},
              except: [:index, :show], shallow: :true

    resources :mc_questions,
              defaults: { q_type: 'McQuestion'},
              except: [:index, :show], shallow: :true

    resources :questions,
              only: [:index], shallow: :true

    resources :survey_responses, only: [:new, :create], shallow: :true

    resources :results, only: [:show], shallow: :true

  end

end

app/models/mc_option.rb
class McOption < ActiveRecord::Base
  belongs_to :mc_question
end

app/models/mc_question.rb
class McQuestion < ActiveRecord::Base
  has_one :question, as: :question, dependent: :destroy
  has_one :survey, through: :questions

  has_many :options, class_name: "McOption", dependent: :destroy

  accepts_nested_attributes_for :options
end

app/models/question.rb
class Question < ActiveRecord::Base
  belongs_to :survey
  belongs_to :question, polymorphic: true
  has_many :question_responses
end

app/models/question_response.rb
class QuestionResponse < ActiveRecord::Base
  belongs_to :survey_response
  belongs_to :question
end

app/models/range_question.rb
class RangeQuestion < ActiveRecord::Base
  has_one :question, as: :question, dependent: :destroy
  has_one :survey, through: :questions
end

app/models/results.rb
class Results

  def initialize(survey_id)
    @survey = Survey.find(survey_id)
  end

  def get_results
    results = initialize_results_hash
    question_responses = []

    SurveyResponse.where(survey_id: @survey.id).each do |response|
     response.question_responses.each do |question_response|
        question_responses << question_response
      end
    end

    question_responses.each do |response|
      q = get_question_obj(Question.find(response.question_id))
      if q.class.name == "RangeQuestion"
        results[q][response.answer] += 1
      else
        q.options.each do |option|
          results[q][option.option] += 1 if option.id == response.answer
        end
      end
    end
    results
  end

  private

  def get_question_obj(question)
    question.question_type.classify.constantize.find(question.question_id)
  end

  def initialize_results_hash
    results = {}
    @survey.questions.each do |question|
       q = get_question_obj(question)
       results[q] = {}

       if q.class.name == "McQuestion"
        q.options.each do |option|
          results[q][option.option] = 0
        end

      else
        (q.min..q.max).to_a.each do |n|
          results[q][n] = 0
        end
      end

    end
    results
  end

end

app/models/survey.rb
class Survey < ActiveRecord::Base
  has_many :questions

  has_many :mc_questions,
            through: :questions,
            source: :question,
            source_type: 'McQuestion'

  has_many :range_questions,
            through: :questions,
            source: :question,
            source_type: 'RangeQuestion'

  has_many :survey_responses
end

app/models/survey_response.rb
class SurveyResponse < ActiveRecord::Base
  belongs_to :survey
  has_many :question_responses
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @survey = Survey.find(params[:survey_id])
  end


end

app/controllers/results_controller.rb
require 'results'

class ResultsController < ApplicationController
  def show
    # @question_results = []
    # SurveyResponse.where(survey_id: params[:id]).each do |response|
    #   @question_results << response.question_responses
    # end
    @survey = Survey.find(params[:id])
    @results = Results.new(params[:id]).get_results

  end

  private



end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    @survey = Survey.new
  end

  def show
    @survey = Survey.find(params[:id])
    @survey.questions.build
  end

  def index
    @surveys = Survey.all
  end

  def create
    @survey = Survey.new(survey_params)
    if @survey.save
      flash[:success] = "You created a survey :)"
      redirect_to survey_questions_path(survey_id: @survey.id)
    else
      flash.now[:error] = "Something went wrong :("
      render :new
    end
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update(survey_params)
      redirect_to survey_questions_path(survey_id: @survey.id)
    else
      render :edit
    end
  end

  def destroy
    if Survey.find(params[:id]).destroy
      redirect_to surveys_path
    else
      flash[:error] = "Could not delete."
      render :show
    end
  end

  private

    def survey_params
      params.require(:survey).permit(:title, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/mc_options_helper.rb
module McOptionsHelper
end

app/helpers/mc_questions_helper.rb
module McQuestionsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/range_questions_helper.rb
module RangeQuestionsHelper
end

app/helpers/results_helper.rb
module ResultsHelper
end

app/helpers/survey_responses_helper.rb
module SurveyResponsesHelper
  def get_question_object(question)
    question.question_type.classify.constantize.find(question.question_id)
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CreateYourOwnSurvey</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <link rel="icon" type="image/png" href="http://www.clker.com/cliparts/0/6/8/6/11971488431079343407barretr_Pencil.svg.hi.png" />

  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  <!-- Optional theme -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
</head>

<body data-no-turbolink >

  <% flash.each do |type, message| %>
    <div>
      <strong><%= type %>! <%= message %></strong>
    </div>
  <% end %>

  <nav class="nav navbar navbar-default">
    <ul class="nav navbar-nav">
      <li><%= link_to "All Surveys", surveys_path %></li>
      <li><%= link_to "New Survey", new_survey_path %></li>
    </ul>
  </nav>

  <div class="container">
    <%= yield %>
  </div>
</body>
</html>